### ISSUE TITLE
Error when loading spatial structure or passive transport of pregnant woman in MoBi into an existing nonpregnant simulation

### ISSUE THREAD

**Issue by EAalgh** [Open-Systems-Pharmacology/Pregnancy-Models#17]
Application:
MoBi® 9.1.1

'>' is an unexpected token. The expected token is '='. Line 82, position 90.

Stack trace:
```
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at MoBi.Presentation.Tasks.SerializationTask.LoadMany[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.Interaction.InteractionTask.LoadItems[T](String filename)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.LoadItems(String filename)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.adddItemsToProjectFromFile(String filename, TParent parent, IBuildingBlock buildingBlockWithFormulaCache)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.AddExisting(TParent parent, IBuildingBlock buildingBlockWithFormulaCache)
   at MoBi.Presentation.UICommand.AddExistingCommandForBase`1.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by AndreDlm** [comment]
Dear @EAalgh,

please make sure you load the `pkml` files via the context menu (right click) of the spatial structure (or passive transports) building block section:
![image](https://user-images.githubusercontent.com/26541603/123997166-607a8800-d9d0-11eb-981e-49b8121f911b.png)

I tried it with MoBi version 9.1.1 and it works fine - I hope this helps!

André

**Comment by AndreDlm** [comment]
Please also make sure you have downloaded the `pkml` files as described here: https://github.com/Open-Systems-Pharmacology/Pregnancy-Models/issues/5

**Comment by EAalgh** [comment]
Thanks a lot. 
It worked when I downloaded all the related files as Zip and uploaded the spatial structure and passive transport of pregnant woman form the extracted Zip file.
