### ISSUE TITLE
Issue with Pregnancy model in MoBi

### ISSUE THREAD

**Issue by mmalsmadi** [Open-Systems-Pharmacology/Pregnancy-Models#26]

**Comment by mmalsmadi** [comment]
any thoughts?

**Comment by mmalsmadi** [comment]
attached are the files I am working on

[1983 Justins Mother IM.zip](https://github.com/Open-Systems-Pharmacology/Pregnancy-Models/files/10196738/1983.Justins.Mother.IM.zip)

**Comment by mmalsmadi** [comment]
Can you please provide help!!!!!

I tried the new spatial structure and passive transport available here
https://github.com/Open-Systems-Pharmacology/Pregnancy-Models/blame/master/BuildingBlocks/PassiveTransport_Pregnancy.pkml

and I got the following error message


Application:
MoBi® 11.0.138

'>' is an unexpected token. The expected token is '='. Line 17, position 76.

Stack trace:
```
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at MoBi.Presentation.Tasks.SerializationTask.LoadMany[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.Interaction.InteractionTask.LoadItems[T](String filename)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.LoadItems(String filename)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.adddItemsToProjectFromFile(String filename, TParent parent, IBuildingBlock buildingBlockWithFormulaCache)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.AddExisting(TParent parent, IBuildingBlock buildingBlockWithFormulaCache)
   at MoBi.Presentation.UICommand.AddExistingCommandForBase`1.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by Yuri05** [comment]
Please make sure that you download the file [PassiveTransport_Pregnancy.pkml](https://raw.githubusercontent.com/Open-Systems-Pharmacology/Pregnancy-Models/master/BuildingBlocks/PassiveTransport_Pregnancy.pkml) and NOT the html page.

**Comment by mmalsmadi** [comment]
I already used the .pkml files not the html files


Regards,

Mo'tasem Alsmadi, PhD

Associate Professor
Department of Pharmaceutical Technology
Faculty of Pharmacy
Jordan University of Science & Technology
P.O.Box 3030 - Irbid 22110, Jordan
Phone: +96227201000    Ext. 23522
________________________________

**Comment by Yuri05** [comment]
I just checked it: all pkml files can be loaded in MoBi. The error above comes if you try to load a html file.

To properly load a file from GitHub:
* Go to the file you want to download.
* Click it to view the contents within the GitHub UI.
* In the top right, right click the `Raw `button or the `Download `button 
* Save as...

**Comment by mmalsmadi** [comment]
Thanks, now I was able to load the spatial structure and passive transport files, 
But, when I tried to set the new simulation based on the original simulation merged with pregnancy files after excluding the metabolic enzymes and undefined liver molecules from the molecule start values for the nine pregnancy-specific compartments in addition to the bone, I got the following error message

![image](https://user-images.githubusercontent.com/37537530/207904841-22ee9912-2948-458c-ab53-4a3e7b507f4b.png)

Did I miss anything?
