### ISSUE TITLE
Error with pregnancy PassiveTransport_PregnantWoman.pkml

### ISSUE THREAD

**Issue by mmalsmadi** [Open-Systems-Pharmacology/Pregnancy-Models#5]
I downloaded the file 
PassiveTransport_PregnantWoman.pkml
Then, when I tried to load this file in Mobi according the procedure described in:
"Applied Concepts in PBPK Modeling: How to Extend an Open Systems Pharmacology Model to the Special Population of Pregnant Women "

I got the following error message:
Application:
MoBi® 8.0.21

'>' is an unexpected token. The expected token is '='. Line 53, position 69.

Stack trace:
```
at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.ReadElementFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XElement.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XElement.Load(String uri, LoadOptions options)
   at MoBi.Presentation.Tasks.SerializationTask.LoadMany[T](String fileName, Boolean resetIds)
   at MoBi.Presentation.Tasks.Interaction.InteractionTask.LoadItems[T](String filename)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.LoadItems(String filename)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.adddItemsToProjectFromFile(String filename, TParent parent, IBuildingBlock buildingBlockWithFormulaCache)
   at MoBi.Presentation.Tasks.Interaction.InteractionTasksForChildren`3.AddExisting(TParent parent, IBuildingBlock buildingBlockWithFormulaCache)
   at MoBi.Presentation.UICommand.AddExistingCommandForBase`1.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by Yuri05** [comment]
It seems that you have downloaded not the file `PassiveTransport_PregnantWoman.pkml` but the **web page** containing the file (a html) 
To download the file properly: click on the "Raw" button first; then save the file
![grafik](https://user-images.githubusercontent.com/25061876/81432575-780b0780-9163-11ea-873d-24e5b20fa002.png)

**Comment by Yuri05** [comment]
P.S. If you need to download many files: the easiest way is to download the whole repository as a single ZIP file:
![grafik](https://user-images.githubusercontent.com/25061876/81433049-3dee3580-9164-11ea-90a7-3dc933c4bddf.png)

**Comment by mmalsmadi** [comment]
Many thanks
It worked

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
